### ISSUE TITLE
fdrtools package for lfdr?

### ISSUE THREAD

**Issue by lpantano** [kdkorthauer/benchmarkfdr-shiny#2]
Hi!

thanks for this work, it helped me a lot in a recent analysis I was doing. I noticed there is LFDR in the table but not R package, it says `none` in the paper. But I think in the other figure is referred to as being done with fdrtools. I just wanted to confirm if the `lfdr` in the figures correspond to that package, and the table was a typo. Or is there another method to calculate the lfdr?

thanks!

**Comment by kdkorthauer** [comment]
Hi @lpantano,

I'm glad you found this work helpful. Yes, the method LFDR (Cai's local fdr) as described in the Cai and Sun (2009) does not provide an R package implementation. However, it is pretty straightforward to implement it, which we do using the `fdrtools` package applied to binned data (note that this implementation was taken from the IHW paper). Even though the implementation makes use of the `fdrtools` package, lfdr is really applying it in a nonstandard way. We only considered the R package available if there exists an R package specifically for that method.

Hope that helps!

Best,
Keegan

**Comment by lpantano** [comment]
Thank you for the quick reply. I see the issue is to accept a covariate to correct the p-values. 

By any chance did anybody look at the option in fdrtools that uses the statistics to calculate the lfdr? I know is outside the scope of the paper and package since all are trying to use the p-value as input, but just in case, somebody played with that. 

I am using that option since my p-value is not uniform at all, and the genes I get with lfdr < 0.05 makes sense when I plot them, not sure If there is any flaw. 

Anyway, thanks for the study and the app.

**Comment by kdkorthauer** [comment]
We did not compare results using statistics as input to the fdrtool package. As you point out, this was beyond the scope of our investigation as we were focused on the impact of using a covariate.
